# Home Page
sdf_billetterie_homepage:
    path:     /
    defaults:
        _controller: SDFBilletterieBundle:Pages/Pages:home
    methods: GET

### Authentication
sdf_billetterie_cas_callback:
    path:     /cas/callback
    defaults:
        _controller: SDFBilletterieBundle:Authentication:casCallback
    methods: GET

sdf_billetterie_login_check:
    path:     /login_check
    defaults:
        _controller: SDFBilletterieBundle:Authentication:loginCheck
    methods: POST

sdf_billetterie_logout:
    path:     /logout

### Subscription
sdf_billetterie_subscription:
    path:     /subscribe
    defaults:
        _controller: SDFBilletterieBundle:Authentication:subscription
    methods: GET

sdf_billetterie_subscription_check:
    path:     /subscribe/check
    defaults:
        _controller: SDFBilletterieBundle:Authentication:subscriptionCheck
    methods: POST

### Regular pages
sdf_cgv:
    path:     /cgv
    defaults:
        _controller: SDFBilletterieBundle:Pages/Pages:legals
    methods: GET

### Tickets specific pages
sdf_billetterie_tickets:
    resource: @SDFBilletterieBundle/Resources/config/routing/billetterie/tickets.yml
    prefix: /tickets

### Payment pages
sdf_billetterie_checkout:
    resource: @SDFBilletterieBundle/Resources/config/routing/billetterie/checkout.yml
    prefix: /checkout

sdf_validationTest:
    path:     /payutcbugtest
    defaults: { _controller:SDFBilletterieBundle:Pages/Ticketing:testbug }

sdf_getEmailsNonValides:
    path:     /getEmailsNonValides
    defaults: { _controller:SDFBilletterieBundle:Pages/Ticketing:getEmailsNonValide }

sdf_checkIfBilletValide:
    path:     /billetcheck/barcode/{id}
    defaults: { _controller:SDFBilletterieBundle:Pages/Ticketing:checkValidBarcode }

sdf_billetterie_checkBilletNumValide:
    path:     /billetcheck/numbillet/{id}
    defaults: { _controller:SDFBilletterieBundle:Pages/Ticketing:checkValidNumBillet }

sdf_billetterie_checkByNamePortion:
    path:     /billetcheck/namesearch/{name}
    defaults: { _controller:SDFBilletterieBundle:Pages/Ticketing:checkByNamePortion }

sdf_billetterie_checkNFC:
    path:     /billetcheck/nfc/{id}
    defaults: { _controller:SDFBilletterieBundle:Pages/Ticketing:getNFCAssociatedBillets }

sdf_billetterie_sendEmailInfos:
    path:     /sendAllInfos
    defaults: { _controller:SDFBilletterieBundle:Pages/Ticketing:sendMailInfos }

sdf_billetterie_validateBillet:
    path:     /billetcheck/validate/{id}
    defaults: { _controller:SDFBilletterieBundle:Pages/Ticketing:validateBillet }

### Administration
sdf_billetterie:
    resource: @SDFBilletterieBundle/Resources/config/routing/billetterie/admin.yml
    prefix: /admin