sdf_billetterie_administration:
    path:     /
    defaults:
        _controller: SDFBilletterieBundle:Pages/Admin/Pages:home
    methods: GET

sdf_billetterie_administration_stats:
    path:     /stats
    defaults:
        _controller: SDFBilletterieBundle:Pages/Admin/Pages:stats
    methods: GET
