sdf_billetterie_checkout_price:
    path:     /{priceId}
    defaults:
        _controller: SDFBilletterieBundle:Pages/Checkout:checkoutTicket
    methods: GET

sdf_billetterie_checkout_price_check:
    path:     /{priceId}/check
    defaults:
        _controller: SDFBilletterieBundle:Pages/Checkout:checkoutTicketCheck
    methods: POST

sdf_billetterie_checkout_ticket_validate:
    path:     /{id}/validate
    defaults:
        _controller: SDFBilletterieBundle:Pages/Ticketing:validate
    methods: GET

sdf_billetterie_checkout_ticket_payutc_callback:
    path:     /{id}/callback
    defaults:
        _controller: SDFBilletterieBundle:Pages/Checkout:handlePayutcCallback
    methods: GET