sdf_billetterie_checking_ticket_barcode_validity:
    path:     /{id}/barcode
    defaults:
        _controller: SDFBilletterieBundle:Pages/Checking:checkTicketBarcodeValidity
    methods: GET

sdf_billetterie_checking_ticket_informations:
    path:     /{id}/informations
    defaults:
        _controller: SDFBilletterieBundle:Pages/Checking:retrieveTicketInformations
    methods: GET

sdf_billetterie_checking_ticket_associated_tickets:
    path:     /{id}/associated_tickets
    defaults:
        _controller: SDFBilletterieBundle:Pages/Checking:getOwnerAssociatedTicketsAction
    methods: GET

sdf_billetterie_checking_ticket_check_in:
    path:     /{id}/check_in
    defaults:
        _controller: SDFBilletterieBundle:Pages/Checking:checkInTicket
    methods: GET