sdf_billetterie_ticket_print:
    path:     /{id}/print
    defaults:
        _controller: SDFBilletterieBundle:Pages/Ticketing:printTicket
    methods: GET

sdf_billetterie_ticket_edit:
    path:     /{id}/edit
    defaults:
        _controller: SDFBilletterieBundle:Pages/Ticketing:editTicket
    methods: GET

sdf_billetterie_ticket_update:
    path:     /{id}/edit
    defaults:
        _controller: SDFBilletterieBundle:Pages/Ticketing:updateTicket
    methods: POST