sdf_billetterie_ticket_print:
    path:     /{id}/print
    defaults:
        _controller: SDFBilletterieBundle:Pages/Ticketing:printTicket
    methods: GET

sdf_billetterie_ticket_edit:
    path:     /{id}/edit
    defaults:
        _controller: SDFBilletterieBundle:Pages/Ticketing:editTicket
    methods: GET

sdf_billetterie_ticket_update:
    path:     /{id}/edit
    defaults:
        _controller: SDFBilletterieBundle:Pages/Ticketing:updateTicket
    methods: POST

sdf_billetterie_ticket_transaction_retry:
    path:     /{id}/transaction/retry
    defaults:
        _controller: SDFBilletterieBundle:Pages/Ticketing:retryTransaction
    methods: GET

sdf_billetterie_ticket_transaction_cancel:
    path:     /{id}/transaction/cancel
    defaults:
        _controller: SDFBilletterieBundle:Pages/Ticketing:cancelTransaction
    methods: GET