sdf_billetterie_administration_constraint_new:
    path:     /new
    defaults:
        _controller: SDFBilletterieBundle:Pages/Admin/Entities/Constraints:new
    methods: GET

sdf_billetterie_administration_constraint_create:
    path:     /create
    defaults:
        _controller: SDFBilletterieBundle:Pages/Admin/Entities/Constraints:create
    methods: POST
