sdf_billetterie_administration_journey_new:
    path:     /new
    defaults:
        _controller: SDFBilletterieBundle:Pages/Admin/Entities/Journeys:new
    methods: GET

sdf_billetterie_administration_journey_create:
    path:     /create
    defaults:
        _controller: SDFBilletterieBundle:Pages/Admin/Entities/Journeys:create
    methods: POST
