sdf_billetterie_administration_price_group_new:
    path:     /new
    defaults:
        _controller: SDFBilletterieBundle:Pages/Admin/Entities/PriceGroups:new
    methods: GET

sdf_billetterie_administration_price_group_create:
    path:     /create
    defaults:
        _controller: SDFBilletterieBundle:Pages/Admin/Entities/PriceGroups:create
    methods: POST
