sdf_billetterie_administration_ticket_new:
    path:     /new
    defaults:
        _controller: SDFBilletterieBundle:Pages/Admin/Entities/Tickets:new
    methods: GET

sdf_billetterie_administration_ticket_create:
    path:     /create
    defaults:
        _controller: SDFBilletterieBundle:Pages/Admin/Entities/Tickets:create
    methods: POST
