sdf_billetterie_homepage:
    path:     /billetterie
    defaults: { _controller: SDFBilletterieBundle:Default:index }

sdf_billetterie_homepage_connexionError:
    path:     /billetterie/connexionError
    defaults: { _controller: SDFBilletterieBundle:Default:errorIndex }

sdf_billetterie_deconnexion:
    path:  /billetterie/deconnexion
    defaults: { _controller: SDFBilletterieBundle:connexion:deco }

sdf_billetterie_administration:
    path:     /billetterie/admin
    defaults: { _controller: SDFBilletterieBundle:connexion:admin }

sdf_billetterie_connexionCAS:
    path:     /billetterie/connexion
    defaults: { _controller: SDFBilletterieBundle:connexion:connexionCAS }

sdf_billetterie_connexionExt:
    path:     /billetterie/connexionExt
    defaults: { _controller: SDFBilletterieBundle:connexion:connexionExt }

sdf_billetterie_creationCompte:
    path:     /billetterie/creationCompte
    defaults: { _controller: SDFBilletterieBundle:connexion:creationCompte }

sdf_billetterie_formulaireCreationCompte:
    path:     /billetterie/creationCompte/check
    defaults: { _controller: SDFBilletterieBundle:connexion:verifFormulaire }

sdf_billetterie_indexBilletterie:
    path:     /billetterie/index/{message}
    defaults: { _controller: SDFBilletterieBundle:billet:listeBillets }

sdf_billetterie_accessBillet:
    path:     /billetterie/billetid/{id}
    defaults: { _controller: SDFBilletterieBundle:billet:accessBillet }

sdf_billetterie_paramBillet:
    path:     /billetterie/billetid/param/{id}
    defaults: { _controller: SDFBilletterieBundle:billet:paramBillet }

sdf_billetterie_changeParamBillet:
    path:     /billetterie/billetid/change/{id}
    defaults: { _controller: SDFBilletterieBundle:billet:changedParamBillet }

sdf_billetterie_achatBillet:
    path:     /billetterie/buy/{typeBillet}
    defaults: { _controller:SDFBilletterieBundle:billet:buyBillet }

sdf_billetterie_callbackPayUTC:
    path:     /billetterie/buy/redirection/{token}
    defaults: { _controller:SDFBilletterieBundle:billet:payUTCcallback }

sdf_billetterie_callbackDePAYUTC:
    path:     /billetterie/buy/callback/{id}
    defaults: { _controller:SDFBilletterieBundle:billet:callbackFromPayutc }

sdf_billetterie_callbackDePAYUTCByID:
    path:     /billetterie/buy/callbackById/{id}
    defaults: { _controller:SDFBilletterieBundle:billet:callbackFromPayutcById }

sdf_billetterie_routingPostPaiement:
    path:     /billetterie/routing/{id}
    defaults: { _controller:SDFBilletterieBundle:billet:routingPostPay }

sdf_billetterie_checkTarifs:
    path:     /billetterie/tarifs
    defaults: { _controller:SDFBilletterieBundle:billet:tarifs }

sdf_billetterie_checkNavettes:
    path:     /billetterie/navettes
    defaults: { _controller:SDFBilletterieBundle:billet:checkNavettes }

sdf_billetterie_contrainteTarif:
    path:     /billetterie/tarifs/contraintes
    defaults: { _controller:SDFBilletterieBundle:billet:checkContraintes }

sdf_billetterie_trajetNavette:
    path:     /billetterie/navettes/trajets
    defaults: { _controller:SDFBilletterieBundle:billet:checkTrajetsNavette }

sdf_billetterie_evenements:
    path:     /billetterie/tarifs/event
    defaults: { _controller:SDFBilletterieBundle:billet:checkEvent }

sdf_billetterie_billetsAdmin:
    path:     /billetterie/billetsAdmin
    defaults: { _controller:SDFBilletterieBundle:billet:billetAdmin }

sdf_billetterie_sendAdminStats:
    path:     /billetterie/adminStats
    defaults: { _controller:SDFBilletterieBundle:Default:adminStats }

sdf_billetterie_relancerTransaction:
    path:     /billetterie/relanceTransaction/{id}
    defaults: { _controller:SDFBilletterieBundle:billet:relancerTransaction }

sdf_billetterie_annulerBilletInvalide:
    path:     /billetterie/annulerBilletNonValide/{id}
    defaults: { _controller:SDFBilletterieBundle:billet:annulerBilletInvalide }

sdf_cgv:
    path:     /cgv
    defaults: { _controller:SDFBilletterieBundle:Default:getCGV }

sdf_validationTest:
    path:     /billetterie/payutcbugtest
    defaults: { _controller:SDFBilletterieBundle:billet:testbug }

sdf_getEmailsNonValides:
    path:     /billetterie/getEmailsNonValides
    defaults: { _controller:SDFBilletterieBundle:billet:getEmailsNonValide }

sdf_checkIfBilletValide:
    path:     /billetterie/billetcheck/barcode/{id}
    defaults: { _controller:SDFBilletterieBundle:billet:checkValidBarcode }

sdf_billetterie_checkBilletNumValide:
    path:     /billetterie/billetcheck/numbillet/{id}
    defaults: { _controller:SDFBilletterieBundle:billet:checkValidNumBillet }

sdf_billetterie_checkByNamePortion:
    path:     /billetterie/billetcheck/namesearch/{name}
    defaults: { _controller:SDFBilletterieBundle:billet:checkByNamePortion }

sdf_billetterie_checkNFC:
    path:     /billetterie/billetcheck/nfc/{id}
    defaults: { _controller:SDFBilletterieBundle:billet:getNFCAssociatedBillets }

sdf_billetterie_sendEmailInfos:
    path:     /billetterie/sendAllInfos
    defaults: { _controller:SDFBilletterieBundle:billet:sendMailInfos }

sdf_billetterie_validateBillet:
    path:     /billetterie/billetcheck/validate/{id}
    defaults: { _controller:SDFBilletterieBundle:billet:validateBillet }